spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: Wsxasd77_
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver